-- Seed known source/platform profiles. These are settings, not parser code, so
-- platform-specific representation rules can be changed without code edits.

INSERT INTO ingest.source_profiles (
  profile_key,
  parser_profile,
  host,
  event_path_prefix,
  competition_stream,
  representation_primary,
  settings
) VALUES
  (
    'denkova_staviski_2013_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2013/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2014_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2014/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2014_nonisu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2014/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2015_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2015/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2015_nonisu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2015/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2015_isucs',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2015/ISUCS',
    'ISUCS',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2016_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2016/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2016_nonisu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2016/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2017_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2017/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2017_nonisu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2017/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2018_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2018/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false},"index_wrapper":"results_js","resolved_index":"pages/main.htm"}'::jsonb
  ),
  (
    'denkova_staviski_2018_nonisu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2018/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false},"index_wrapper":"results_js","resolved_index":"pages/main.htm"}'::jsonb
  ),
  (
    'denkova_staviski_2019_isu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2019/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false},"index_wrapper":"results_js","resolved_index":"pages/main.html"}'::jsonb
  ),
  (
    'denkova_staviski_2019_nonisu',
    'old_isucalcfs',
    'cup.clubdenkovastaviski.com',
    '2019/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false},"index_wrapper":"results_js","resolved_index":"pages/main.html"}'::jsonb
  ),
  (
    'denkova_staviski_2024_isu',
    'fs_manager',
    'cup.clubdenkovastaviski.com',
    '2024/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'denkova_staviski_2024_nonisu',
    'fs_manager',
    'cup.clubdenkovastaviski.com',
    '2024/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'sofia_trophy_2026_isu',
    'fs_manager',
    'sofia-trophy.clubdenkovastaviski.com',
    '2026/ISU',
    'ISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'sofia_trophy_2026_nonisu',
    'fs_manager',
    'sofia-trophy.clubdenkovastaviski.com',
    '2026/NonISU',
    'NonISU',
    'nation',
    '{"representation":{"primary":"nation","store_nation":true,"store_club":false}}'::jsonb
  ),
  (
    'ice_peak_trophy_2026',
    'fs_manager',
    'www.bsf.bg',
    'figure-skating/ice-peak-trophy/18-19.04.2026',
    'club',
    'club',
    '{"representation":{"primary":"club","store_nation":true,"store_club":true}}'::jsonb
  )
ON CONFLICT (profile_key) DO UPDATE SET
  parser_profile = EXCLUDED.parser_profile,
  host = EXCLUDED.host,
  event_path_prefix = EXCLUDED.event_path_prefix,
  competition_stream = EXCLUDED.competition_stream,
  representation_primary = EXCLUDED.representation_primary,
  settings = EXCLUDED.settings,
  updated_at = now();
